### PR TITLE
pick_best() speedup without full std::swap

### PR DESCRIPTION
**Pull request by atumanian**

### CODE REVIEW

**Comment by Hexik** [comment]
hi,thanks for the inspiration, I hope the quickest/simplest version of the zillion times invoked function pick_best() is below. The loop is stripped source from std::max_element() and the finish is useful 2/3 part of std::swap() speedup approx 0.5% from one function is not so bad if you take into account how mature is the Stockfish codebase, Marco reject my commit so I sadly deleted the branch, I guess you will face the same situation ;-)

# 

Move pick_best( ExtMove *begin, ExtMove *end )
{
      assert(begin < end);

```
  ExtMove *ptr = begin;
  ExtMove *iter = begin;

  while (++iter < end)
      if (ptr->value < iter->value)
          ptr = iter;

  ExtMove res = *ptr;
  *ptr = *begin;
  return res;
```

}

Less aggresive code change, cca 0.4% speedup with omitted redundant assignment into "begin" position, from my point of view still good enough to commit.
Move pick_best( ExtMove *begin, ExtMove *end )
{
    auto ptr = std::max_element( begin, end );

```
ExtMove res = *ptr;
*ptr = *begin;
return res;
```

}

**Comment by LichessMaster** [comment]
Dear Aram,

I want to apologize for sending the opposite message in @mcostalba repo. I had to send this message to make sure they don't delete my messages.

It is important that we can confidently rely on each other to complete our assignments. When I made a mistake, I let you down.

I understand that I have damaged our working relationship. However, I greatly value you as a colleague, and I believe that we have worked well together as a team in the past. I hope that you will be willing to work together in the future.

@atumanian Please let me know if there is anything else I can do to make this possible.

Sincerely,

Sara

**Comment by atumanian** [comment]
@LichessMaster
Hi, Sara!
No problem. Thank you for your appreciation of our collaboration. I'm willing to work together with you.
But won't it be convenient if we talk by email instead of GitHub? You can write to me: `aram [dot] tumanian [at] gmail [dot] com`

**Comment by atumanian** [comment]
Hi, @BehindTheEyes 
There are many services which provide free email accounts. You can obtain a new one for conversations.
I'm not registered in StackOverflow, so I don't know if there is a chat there.
But you can register in [discord.com](https://discord.com) - you can send private messages there.

**Comment by Photoshop2023** [comment]
Hi @atumanian , This is my private account ,  we can send private messages here.

Also I can create a private repository if you want ...?!

From my opinion , You are the best Stockfish author , I love you very much ❤️

**Comment by atumanian** [comment]
Hi, @Photoshop2023 
Thank you :heart: 
You can create a private repository if you want, but I don't understand why you don't want to talk outside GitHub.

**Comment by ginkgo20** [comment]
@atumanian Please see this :

- https://github.com/AndyGrant/Ethereal/issues/200

Andrew Grant blocked me because I said to him that "Why Ethereal engine is not open source"?

**After 5 years , Andy decide that chess engine should not be open source .....**

I hope that you will provide answers to all these questions in your proposal.

**Comment by atumanian** [comment]
@ginkgo20
Sorry, I don't understand what my proposal you mean.

**Comment by ginkgo20** [comment]
This proposal that chess engine should be open source 😂

**Comment by ginkgo20** [comment]
See this 

- https://github.com/lucametehau/CloverEngine/issues/127

He is very rude boy and then blocked, I want to add him in new list...

**Comment by ginkgo20** [comment]
_No need to be nice with you, many community members where already nice enough, whereas you just wanted to troll. You are either a functional analphabet and do not understand what an issue is or you are here just to troll, in both cases your presence here is not welcome and please don't feel like you are helping or accomplishing something. All you are doing is making a fool of yourself, which you already are, a low life that trolls a relatively small community, because their parents don't love them. Have a shit day!_

_Originally posted by @lucametehau in https://github.com/lucametehau/CloverEngine/issues/127#issuecomment-1586182511_

**Comment by ginkgo20** [comment]
@atumanian 
Ինչու դեռ ամուսնացած չեք:

**Pull request merged**
