### PR TITLE
FishCooking

### PR DESCRIPTION
**Pull request by ghost**
Hi @atumanian, the entire repo we were commenting has been deleted!

https://github.com/romstad/Fairy-Stockfish 

I don't know who deleted it but we are continuing our goal

I found these two pulls is useful for fishcooking

_1-a wrong pull request that vondele merge it & blocked_
https://github.com/official-stockfish/Stockfish/pull/4195

_2-a true pull request that vondele don't merge it_
https://github.com/official-stockfish/Stockfish/pull/4277

@vondele blocked us for disagreeing with his comments

> I've blocked @atumanian in light of this discussion.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4195#issuecomment-1279968617_

I hope this helps your topic in fishcooking

### CODE REVIEW

**Comment by FishChess** [comment]
I found these two pulls is useful for fishcooking

1-a wrong pull request that vondele merge it
https://github.com/official-stockfish/Stockfish/pull/4195

2-a true pull request that vondele don't merge it
https://github.com/official-stockfish/Stockfish/pull/4277

@vondele blocked us after disagreeing with his comments

I hope this helps your topic in fishcooking

**Comment by FishChess** [comment]
I found another true pull from @nguyenpham that vondele don't merge it

> I won't merge this, we're not particularly keen on adding functionality that is not needed, or can easily be derived externally.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/3356#issuecomment-792277945_

But @nguyenpham didn't defend himself and that's why he wasn't blocked

**Comment by FishChess** [comment]
In the issues section , Also I found a bug in all stockfish version (Stockfish 1 - Stockfish 15) but @vondele said it's not issue :

>  no, it is not an important issue, it is a non-issue. Please stop adding comments on this topic.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4262#issuecomment-1342175690_

**Also another developers said it is better to solve the problem :**

> It that case there should be a comment in the source code about this it seems to me. But personally, from a software engineering point of view, I would prefer if this requirement were removed.
> 
> _Originally posted by @vdbergh in https://github.com/official-stockfish/Stockfish/issues/4262#issuecomment-1342185793_


> I also think it would be reasonable to add more checks in material.cpp#L76 
> 
> I can implement the required changes if there's a consensus.
> 
> _Originally posted by @Sopel97 in https://github.com/official-stockfish/Stockfish/issues/4262#issuecomment-1342362931_

**but vondele said :**

> I think this just affects the classical code. I see no real point in making this change. Adding a comment near the type values could be done.
> 
> _Originally posted by @vondele in https://github.com/official-stockfish/Stockfish/issues/4262#issuecomment-1343220558_

@atumanian Please include these items in FishCooking

**Comment by atumanian** [comment]
Hi, @FishChess
I have no idea either who deleted the Fairy-Stockfish repo. Anyway, we can discuss the problem here. I'm in the process of writing a post for the Fishcooking forum. I just don't have much spare time, so it can take a couple of days. I'll mention two cases, #4195 and #4277.
I also want to mention https://github.com/glinscott/fishtest/issues/1427 where Onur Zungur closed the issue without any arguments and spoke to me in an humiliating way. Also Vondele wanted it to be closed. It indicates there's no freedom of speech on the Fishtest repo either.

**Comment by atumanian** [comment]
Regarding https://github.com/official-stockfish/Stockfish/issues/4262 , I don't agree with Vondele, but won't you mind I don't mention it in my starting post? In my opinion, this case isn't as outrageous as the other ones. Anyway, you are free to comment and write about it.

**Comment by FishChess** [comment]
> It indicates there's no freedom of speech on the Fishtest repo either.

Yes, also I had a fishtets that I wanted to increase knight value but @vondele he stopped it several for no reason
>  
> you do realize that with NNUE these parameters have essentially no impact?
> 
> _Originally posted by @vondele in https://github.com/glinscott/fishtest/issues/1475#issuecomment-1345182803_

**Comment by fishchess** [comment]
> I also want to mention [glinscott/fishtest#1427](https://github.com/glinscott/fishtest/issues/1427) where Onur Zungur closed the issue without any arguments and spoke to me in an humiliating way. Also Vondele wanted it to be closed. It indicates there's no freedom of speech on the Fishtest repo either.

You are right, there's no freedom of speech on the Fishtest & Stockfish , I think someone should supervise on stockfish ,@vondele blocked everybody that disagree with himself

**Comment by fishchess** [comment]
> Regarding [official-stockfish#4262](https://github.com/official-stockfish/Stockfish/issues/4262) , I don't agree with Vondele, but won't you mind I don't mention it in my starting post? 

Ok , don't mention it, this case isn't as outrageous as the other ones.

**Comment by atumanian** [comment]
> > It indicates there's no freedom of speech on the Fishtest repo either.
> 
> Yes, also I had a fishtets that I wanted to increase knight value but @vondele he stopped it several for no reason
> 
> > you do realize that with NNUE these parameters have essentially no impact?
> > _Originally posted by @vondele in [glinscott/fishtest#1475 (comment)](https://github.com/glinscott/fishtest/issues/1475#issuecomment-1345182803)_

Ok, your opponents may be objectively right in this case, but calling you a troll while you're trying to understand things isn't polite behaviour on their part.

**Comment by atumanian** [comment]
Done! I've created [a topic in Fishcooking](https://groups.google.com/g/fishcooking/c/e05Imm5ivqE).

**Comment by FishChess** [comment]
Thanks @atumanian , I believe in you, I am sure we will succeed

This song dedicated to you


https://user-images.githubusercontent.com/118218359/208031957-d35747c1-b3d6-4dad-ae47-b5a79488d4ec.mp4

**Comment by FishChess** [comment]
> I see nothing wrong in testing a version with an increased knight value. You still have to set `Use NNUE=true` because this is the default value and the engine is much weaker otherwise. Even if NNUE is enabled, the classical evaluation is selected conditionally by the line (evaluate.cpp:1059):

```
 bool useClassical = !useNNUE || (pos.count<ALL_PIECES>() > 7 && abs(psq) > 1760);
```
> Moreover, `pos.non_pawn_material()`, which depends on the piece values, is used in [evaluate.cpp:1066](https://github.com/official-stockfish/Stockfish/blob/7cf93f8b7101e5cf5df3f7921861f27b3beb9525/src/evaluate.cpp#L1066) and [nnue/evaluate_nnue.cpp:146](https://github.com/official-stockfish/Stockfish/blob/7cf93f8b7101e5cf5df3f7921861f27b3beb9525/src/nnue/evaluate_nnue.cpp#L146). Therefore, I don't agree the piece values have no impact with NNUE.

yes I know this but @vondele failed my accound me in fishtest 

https://tests.stockfishchess.org/tests/view/63942b1988432ad6ae39d4d1

https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840

**Comment by FishChess** [comment]
> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12

> The first one is correct. But how is it related to our topic?

I explained this example to show different viewpoint, The first one is correct. Also, The Second one is correct

**Comment by FishChess** [comment]
If you want, I can write these sentences in the fishtest, but the administrators may get upset and blocked again

**Comment by FishChess** [comment]
I bring this example because @vondele blocked us because of her different viewpoint

**Comment by fishchess** [comment]
**I prefer to write answer of question fishtest in here**

> I see nothing wrong in testing a version with an increased knight value. You still have to set `Use NNUE=true` because this is the default value and the engine is much weaker otherwise. Even if NNUE is enabled, the classical evaluation is selected conditionally by the line (evaluate.cpp:1059): Therefore, I don't agree the piece values have no impact with NNUE.

yes I know this but @vondele failed my test in fishtest  

in first test nnue is enable but bench is low

https://tests.stockfishchess.org/tests/view/63942b1988432ad6ae39d4d1

in second test nnue is disable & bench is normal

https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840

probably in third test also found a problem to failed it 

https://tests.stockfishchess.org/tests/view/.....

> ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> ## 1 + 2 + 3 + 4 + 5 + ... = -1/12
> The first one is correct. But how is it related to our topic?

I explained this example to show different viewpoint, The first one is correct. Also, The Second one is correct

I bring this example because @vondele blocked us for disagree comment (different viewpoint)

**Comment by atumanian** [comment]
> in second test nnue is disable & bench is normal
> 
> https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840

Sorry, I can't see the differences between the versions in this test, because the test repository has been deleted. So I can't review and say if there was a reason to stop the test. But if an admin stops, he should at least explain the reason.

> 
> probably in third test also found a problem to failed it
> 
> https://tests.stockfishchess.org/tests/view/.....

Sorry, the link is broken.

> 
> > ## 1 + 2 + 3 + 4 + 5 + ... = ∞
> > ## 1 + 2 + 3 + 4 + 5 + ... = -1/12
> > The first one is correct. But how is it related to our topic?
> 
> I explained this example to show different viewpoint, The first one is correct. Also, The Second one is correct
> 
> I bring this example because @vondele blocked us for disagree comment (different viewpoint)

I don't agree both answers are correct in your example, but complete agree that a different viewpoint is not a legitimate reason to block the user.

**Comment by atumanian** [comment]
> Thanks @atumanian , I believe in you, I am sure we will succeed
> 
> This song dedicated to you heart

Thank you for the song and for your support :heart:

**Comment by fishchess** [comment]
> but complete agree that a different viewpoint is not a legitimate reason to block the user.

image

Unfortunately, the fishtest admin (mayble vondele) topic off & spam our comments

> Sorry, I can't see the differences between the versions in this test, because the test repository has been deleted. 

yes, vondele deleted my fishtets immediately to another person don't see failed it

> Sorry, the link is broken.

this was not link, I said this as an example, even if I made a third fishtest, vondele would delete it again

> I don't agree both answers are correct in your example

image

both answers are correct , you can see more  information in wikipedia 

[https://en.wikipedia.org/wiki/1 + 2 + 3 + 4 + ⋯](https://en.wikipedia.org/wiki/1_%2B_2_%2B_3_%2B_4_%2B_%E2%8B%AF
)

**Comment by atumanian** [comment]
> Unfortunately, the fishtest admin (mayble vondele) topic off & spam our comments
> 

Vondele is not an admin in the Fishtest repo. I don't know who did it, possibly Zungur.

> > Sorry, I can't see the differences between the versions in this test, because the test repository has been deleted.
> 
> yes, vondele deleted my fishtets immediately to another person don't see failed it

No, I mean the your repo which you linked in the test has been deleted. If you click on [the link](https://github.com/FishChess/Fish/commit/00320c9b67600eafe8a5aef618df76fa46669875) at the `new_tag` field in [your test's page](https://tests.stockfishchess.org/tests/view/63943d7388432ad6ae39d840), it gives a 404 error.

> 
> > Sorry, the link is broken.
> 
> this was not link, I said this as an example, even if I made a third fishtest, vondele would delete it again
> 

Ok, I understand now. I think there's no point in trying to contribute to the project under such attitude from admins. The only hope is to develop a chess engine without persons like Vondele and Zungur as admins.

> > I don't agree both answers are correct in your example
> 
> image
> 
> both answers are correct , you can see more information in wikipedia

I disagree, but I think it's off-topic. If you are interested, we can discuss it privately or on a dedicated forum.

**Comment by FishChess** [comment]
> The only hope is to develop a chess engine without persons like Vondele and Zungur as admins.

Yes, we must develop a chess engine ,90% stockfish commits are pointless, we can develop a strong chess engine but suggest not open source, also no need for NNUE, we can develop a strong classical engine ,

If you want, I can make private repo for our chess engine or you make repo, it doesn't matter

**Comment by atumanian** [comment]
> > The only hope is to develop a chess engine without persons like Vondele and Zungur as admins.
> 
> Yes, we must develop a chess engine ,**90% of stockfish commits are pointless**, we can develop a strong chess engine but suggest not open source, also no need for NNUE
> 
> I can make private repo for our chess engine ?

You can make a private repo, of course. But I personally am not interested in developing a chess engine which is not open-source.

**Comment by FishChess** [comment]
> But I personally am not interested in developing a chess engine which is not open-source.

most chess engines are not open source, e.g. Komodo,  Fritz, Houdini , Rybka , HIARCS , ....

**Comment by FishChess** [comment]
> You can make a private repo,

if we create open-source chess, vondele copies from our code,  i created a repo and sent you invitation, please accept my invite, thanks

**Comment by fishchess** [comment]
Onur Zungur Closed my true PR in fishtest https://github.com/glinscott/fishtest/pull/1490#issue-1501851950

**Comment by atumanian** [comment]
> Onur Zungur Closed my true PR in fishtest [glinscott/fishtest#1490 (comment)](https://github.com/glinscott/fishtest/pull/1490#issue-1501851950)

Sorry, I don't have much time to review this case. What happened there?

**Comment by atumanian** [comment]
@fishchess
If you want to contact me privately, I can give my contacts. You can also join the [Fishcooking](https://groups.google.com/g/fishcooking) forum. There is no oppression of speech there like in the GitHub repos.

**Comment by ghost** [comment]
Hi @atumanian ,  I created a new account for more privacy 

This users violated the Freedom of speech

_1- Sopel97
2- noobpwnftw
3- vondele
4- zungur
5- Disservin
6- ianfab
7- peregrineshahin
8- snicolet_

It's better if we can discuss about it privately

**Comment by atumanian** [comment]
> 

Hi! We can contact by email or Facebook. It seems GitHub doesn't have a feature of private messages.

**Comment by TheDarkKnightRise** [comment]
I created this account for our goal

They filled our path full of doubt
And wouldn't hear our out
But still we chased our dreams
They told our to quit
But our heart could not resist
And from the darkness came a light
We will shine on tomorrow
Light the way for all to follow
From the darkness we will shine

**Comment by TheDarkKnightRise** [comment]
They filled our path full of doubt
And wouldn't hear our out
But still we chased our dreams
They told our to quit
But our heart could not resist
And from the darkness came a light
We will shine on tomorrow
Light the way for all to follow
From the darkness we will shine

**Comment by ginkgo20** [comment]
@atumanian I think Vondele don't want to work with us , It's the time when we retire from Official_Stockfish
, I hope we could work together in future

**Comment by atumanian** [comment]
@ginkgo20
Yes, I have already retired from Official-Stockfish.

**Comment by ginkgo20** [comment]
@atumanian 
դու ամուսնացած ես?

**Comment by atumanian** [comment]
> դու ամուսնացած ես?

Ոչ, ամուսնացած չեմ։ Ինչու ես հայերե՞ն գրում։ Դու հա՞յ ես։

**Comment by ginkgo20** [comment]
❤️❤️❤️

**Comment by ginkgo20** [comment]
I wanna help to you but some reasons make distance between us.

**Comment by SlowChess** [comment]
Դու իմ լավագույն ընկերն ես

**Pull request closed without merging**
